pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: build
        displayName: 'Build'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'sonar'
            organization: 'rolivaresusach'
            scannerMode: 'Other'
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: true
            sqMavenPluginVersionChoice: 'latest'
            failWhenBugsFound: true
          displayName: SonarCloud Analysis
            
        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'
        - task: sonarcloud-buildbreaker@2
          inputs:
            SonarCloud: 'sonar'
            organization: 'rolivaresusach'