pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: build
        displayName: 'Build'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            testRunTitle: 'Tests'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: CopyFiles@2
          inputs:
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: |
                **/target/*.jar
                **/surefire-reports/*.xml
              targetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: appJar
              publishLocation: 'Container'